# Generated by Django 4.1.5 on 2023-01-30 21:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('name', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Proje Adı')),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='services', verbose_name='Proje Ana Resim')),
                ('image1', models.ImageField(upload_to='services', verbose_name='Resim Detay1')),
                ('image2', models.ImageField(upload_to='services', verbose_name='Resim Detay2')),
                ('image3', models.ImageField(upload_to='services', verbose_name='Resim Detay3')),
                ('image4', models.ImageField(upload_to='services', verbose_name='Resim Detay4')),
                ('description1', ckeditor.fields.RichTextField(null=True, verbose_name='Detay Açıklama')),
                ('service', models.CharField(max_length=50, verbose_name='Hizmet Alanı')),
                ('adres', models.CharField(max_length=100, verbose_name='Yer Neresi')),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='Marka')),
            ],
        ),
    ]
