# Generated by Django 4.1.5 on 2023-01-30 21:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_description2_proje_description1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proje',
            name='description1',
        ),
        migrations.AlterField(
            model_name='proje',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Detay Açıklama'),
        ),
    ]
