# Generated by Django 4.1.5 on 2023-01-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_proje_description1_alter_proje_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='description1',
            field=models.TextField(null=True),
        ),
    ]
