# Generated by Django 4.1.5 on 2023-02-07 09:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_category_description_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Ana Sayfada Gösterilsin Mi'),
        ),
        migrations.AddField(
            model_name='proje',
            name='seodescription',
            field=models.CharField(default=2, max_length=170, verbose_name='Seo Açıklama Kısmı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proje',
            name='seotitle',
            field=models.TextField(max_length=70, null=True, verbose_name='Seo Başlığı'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True, verbose_name='Faaliyet Alanı Açıklama'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=100, null=True, verbose_name='İcon Kodu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Faaliyet Alanı Ekle'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Bu kısım otomatik dolmaktadır.'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='Faaliyet Alanı'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Proje Ekleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İşletme Açıklama'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='description1',
            field=models.TextField(null=True, verbose_name='Ana Sayfa Başlığı'),
        ),
    ]
